/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetWalletPoolsRequest {
    /**
     * If true V2 pools will be present in the response. Default: true
     */
    dex_v2?: boolean;
}
