/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         addr_str: "addr_str",
 *         asset_str: "asset_str"
 *     }
 */
export interface GetWalletAssetRequest {
    addr_str: string;
    asset_str: string;
}
