/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         addr_str: "addr_str",
 *         farm_str: "farm_str"
 *     }
 */
export interface GetWalletFarmRequest {
    addr_str: string;
    farm_str: string;
}
