/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         addr_str: "addr_str",
 *         pool_str: "pool_str"
 *     }
 */
export interface GetWalletPoolRequest {
    addr_str: string;
    pool_str: string;
}
