/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../../../index.js";

export interface GetFeesStatsResponse {
    assets_fee_stats: Stonfi.AssetFeeStatsSchema[];
    /** Time since the stats are requested (YYYY-MM-DDTHH:MM:SS) */
    since: string;
    /** Sum of deposits in usd over the set time period */
    total_accrued_usd?: string;
    /** Sum of withdrawals in usd over the set time period */
    total_withdrawn_usd?: string;
    /** Time until the stats are requested (YYYY-MM-DDTHH:MM:SS) */
    until: string;
}
