/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../../../index.js";

export interface GetOperationStatsUtoipaResponse {
    /** Time since the stats are requested (YYYY-MM-DDTHH:MM:SS) */
    since: string;
    /** Stats of each pool */
    stats: Stonfi.PoolStats[];
    /** Number of unique wallets operated in pool */
    unique_wallets_count: number;
    /** Time until the stats are requested (YYYY-MM-DDTHH:MM:SS) */
    until: string;
}
