/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetStakingStatsResponse {
    gemston_total_supply: string;
    ston_price_usd: string;
    ston_total_supply: string;
    total_staked_ston: string;
}
