/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../../../index.js";

export interface GetWalletStakesResponse {
    minted_gemston: string;
    nfts?: Stonfi.StakeNft[];
    staked_ston: string;
    ston_balance: string;
    voting_power: string;
}
