/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../../../index.js";

export interface GetWalletFarmsResponse {
    farm_list: Stonfi.FarmInfoSchema[];
}
