/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../../../index.js";

export interface GetWalletAssetsResponse {
    asset_list: Stonfi.AssetInfoSchema[];
}
