/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         fromBlock: 1,
 *         toBlock: 1
 *     }
 */
export interface ScreenerEventsRequest {
    /**
     * Block number of the response events start (inclusive)
     */
    fromBlock: number;
    /**
     * Block number of the response events end (inclusive)
     */
    toBlock: number;
}
