/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         address: "address"
 *     }
 */
export interface ScreenerPoolInfoRequest {
    address: string;
}
