/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core/index.js";
import * as Stonfi from "../../../index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Wallets {
    export interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

/**
 * Wallets specific data
 */
export class Wallets {
    protected readonly _options: Wallets.Options;

    constructor(_options: Wallets.Options) {
        this._options = _options;
    }

    /**
     * @param {Stonfi.GetWalletAssetsRequest} request
     * @param {Wallets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.wallets.getWalletAssets({
     *         addr_str: "addr_str"
     *     })
     */
    public getWalletAssets(
        request: Stonfi.GetWalletAssetsRequest,
        requestOptions?: Wallets.RequestOptions,
    ): core.HttpResponsePromise<Stonfi.GetWalletAssetsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWalletAssets(request, requestOptions));
    }

    private async __getWalletAssets(
        request: Stonfi.GetWalletAssetsRequest,
        requestOptions?: Wallets.RequestOptions,
    ): Promise<core.WithRawResponse<Stonfi.GetWalletAssetsResponse>> {
        const { addr_str: addrStr } = request;
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/wallets/${encodeURIComponent(addrStr)}/assets`,
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Stonfi.GetWalletAssetsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.StonfiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StonfiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.StonfiTimeoutError("Timeout exceeded when calling GET /v1/wallets/{addr_str}/assets.");
            case "unknown":
                throw new errors.StonfiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Stonfi.GetWalletAssetRequest} request
     * @param {Wallets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.wallets.getWalletAsset({
     *         addr_str: "addr_str",
     *         asset_str: "asset_str"
     *     })
     */
    public getWalletAsset(
        request: Stonfi.GetWalletAssetRequest,
        requestOptions?: Wallets.RequestOptions,
    ): core.HttpResponsePromise<Stonfi.GetWalletAssetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWalletAsset(request, requestOptions));
    }

    private async __getWalletAsset(
        request: Stonfi.GetWalletAssetRequest,
        requestOptions?: Wallets.RequestOptions,
    ): Promise<core.WithRawResponse<Stonfi.GetWalletAssetResponse>> {
        const { addr_str: addrStr, asset_str: assetStr } = request;
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/wallets/${encodeURIComponent(addrStr)}/assets/${encodeURIComponent(assetStr)}`,
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Stonfi.GetWalletAssetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.StonfiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StonfiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.StonfiTimeoutError(
                    "Timeout exceeded when calling GET /v1/wallets/{addr_str}/assets/{asset_str}.",
                );
            case "unknown":
                throw new errors.StonfiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Stonfi.GetWalletFarmsRequest} request
     * @param {Wallets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.wallets.getWalletFarms({
     *         addr_str: "addr_str"
     *     })
     */
    public getWalletFarms(
        request: Stonfi.GetWalletFarmsRequest,
        requestOptions?: Wallets.RequestOptions,
    ): core.HttpResponsePromise<Stonfi.GetWalletFarmsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWalletFarms(request, requestOptions));
    }

    private async __getWalletFarms(
        request: Stonfi.GetWalletFarmsRequest,
        requestOptions?: Wallets.RequestOptions,
    ): Promise<core.WithRawResponse<Stonfi.GetWalletFarmsResponse>> {
        const { addr_str: addrStr, dex_v2: dexV2, only_active: onlyActive } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (dexV2 !== undefined) {
            _queryParams["dex_v2"] = dexV2?.toString() ?? null;
        }

        if (onlyActive !== undefined) {
            _queryParams["only_active"] = onlyActive?.toString() ?? null;
        }

        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/wallets/${encodeURIComponent(addrStr)}/farms`,
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Stonfi.GetWalletFarmsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.StonfiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StonfiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.StonfiTimeoutError("Timeout exceeded when calling GET /v1/wallets/{addr_str}/farms.");
            case "unknown":
                throw new errors.StonfiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Stonfi.GetWalletFarmRequest} request
     * @param {Wallets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.wallets.getWalletFarm({
     *         addr_str: "addr_str",
     *         farm_str: "farm_str"
     *     })
     */
    public getWalletFarm(
        request: Stonfi.GetWalletFarmRequest,
        requestOptions?: Wallets.RequestOptions,
    ): core.HttpResponsePromise<Stonfi.GetWalletFarmResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWalletFarm(request, requestOptions));
    }

    private async __getWalletFarm(
        request: Stonfi.GetWalletFarmRequest,
        requestOptions?: Wallets.RequestOptions,
    ): Promise<core.WithRawResponse<Stonfi.GetWalletFarmResponse>> {
        const { addr_str: addrStr, farm_str: farmStr } = request;
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/wallets/${encodeURIComponent(addrStr)}/farms/${encodeURIComponent(farmStr)}`,
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Stonfi.GetWalletFarmResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.StonfiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StonfiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.StonfiTimeoutError(
                    "Timeout exceeded when calling GET /v1/wallets/{addr_str}/farms/{farm_str}.",
                );
            case "unknown":
                throw new errors.StonfiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Stonfi.GetFeeVaultsRequest} request
     * @param {Wallets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.wallets.getFeeVaults({
     *         addr_str: "addr_str"
     *     })
     */
    public getFeeVaults(
        request: Stonfi.GetFeeVaultsRequest,
        requestOptions?: Wallets.RequestOptions,
    ): core.HttpResponsePromise<Stonfi.GetFeeVaultsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getFeeVaults(request, requestOptions));
    }

    private async __getFeeVaults(
        request: Stonfi.GetFeeVaultsRequest,
        requestOptions?: Wallets.RequestOptions,
    ): Promise<core.WithRawResponse<Stonfi.GetFeeVaultsResponse>> {
        const { addr_str: addrStr } = request;
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/wallets/${encodeURIComponent(addrStr)}/fee_vaults`,
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Stonfi.GetFeeVaultsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.StonfiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StonfiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.StonfiTimeoutError(
                    "Timeout exceeded when calling GET /v1/wallets/{addr_str}/fee_vaults.",
                );
            case "unknown":
                throw new errors.StonfiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Stonfi.GetWalletOperationsUtoipaRequest} request
     * @param {Wallets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.wallets.getWalletOperationsUtoipa({
     *         addr_str: "addr_str",
     *         since: "2023-06-01T12:34:56",
     *         until: "2023-06-02T23:59:59"
     *     })
     */
    public getWalletOperationsUtoipa(
        request: Stonfi.GetWalletOperationsUtoipaRequest,
        requestOptions?: Wallets.RequestOptions,
    ): core.HttpResponsePromise<Stonfi.GetWalletOperationsUtoipaResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWalletOperationsUtoipa(request, requestOptions));
    }

    private async __getWalletOperationsUtoipa(
        request: Stonfi.GetWalletOperationsUtoipaRequest,
        requestOptions?: Wallets.RequestOptions,
    ): Promise<core.WithRawResponse<Stonfi.GetWalletOperationsUtoipaResponse>> {
        const { addr_str: addrStr, since, until, op_type: opType, dex_v2: dexV2 } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["since"] = since;
        _queryParams["until"] = until;
        if (opType != null) {
            if (Array.isArray(opType)) {
                _queryParams["op_type"] = opType.map((item) => item);
            } else {
                _queryParams["op_type"] = opType;
            }
        }

        if (dexV2 !== undefined) {
            _queryParams["dex_v2"] = dexV2?.toString() ?? null;
        }

        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/wallets/${encodeURIComponent(addrStr)}/operations`,
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Stonfi.GetWalletOperationsUtoipaResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.StonfiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StonfiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.StonfiTimeoutError(
                    "Timeout exceeded when calling GET /v1/wallets/{addr_str}/operations.",
                );
            case "unknown":
                throw new errors.StonfiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Stonfi.GetWalletPoolsRequest} request
     * @param {Wallets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.wallets.getWalletPools({
     *         addr_str: "addr_str"
     *     })
     */
    public getWalletPools(
        request: Stonfi.GetWalletPoolsRequest,
        requestOptions?: Wallets.RequestOptions,
    ): core.HttpResponsePromise<Stonfi.GetWalletPoolsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWalletPools(request, requestOptions));
    }

    private async __getWalletPools(
        request: Stonfi.GetWalletPoolsRequest,
        requestOptions?: Wallets.RequestOptions,
    ): Promise<core.WithRawResponse<Stonfi.GetWalletPoolsResponse>> {
        const { addr_str: addrStr, dex_v2: dexV2 } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (dexV2 !== undefined) {
            _queryParams["dex_v2"] = dexV2?.toString() ?? null;
        }

        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/wallets/${encodeURIComponent(addrStr)}/pools`,
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Stonfi.GetWalletPoolsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.StonfiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StonfiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.StonfiTimeoutError("Timeout exceeded when calling GET /v1/wallets/{addr_str}/pools.");
            case "unknown":
                throw new errors.StonfiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Stonfi.GetWalletPoolRequest} request
     * @param {Wallets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.wallets.getWalletPool({
     *         addr_str: "addr_str",
     *         pool_str: "pool_str"
     *     })
     */
    public getWalletPool(
        request: Stonfi.GetWalletPoolRequest,
        requestOptions?: Wallets.RequestOptions,
    ): core.HttpResponsePromise<Stonfi.GetWalletPoolResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWalletPool(request, requestOptions));
    }

    private async __getWalletPool(
        request: Stonfi.GetWalletPoolRequest,
        requestOptions?: Wallets.RequestOptions,
    ): Promise<core.WithRawResponse<Stonfi.GetWalletPoolResponse>> {
        const { addr_str: addrStr, pool_str: poolStr } = request;
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/wallets/${encodeURIComponent(addrStr)}/pools/${encodeURIComponent(poolStr)}`,
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Stonfi.GetWalletPoolResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.StonfiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StonfiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.StonfiTimeoutError(
                    "Timeout exceeded when calling GET /v1/wallets/{addr_str}/pools/{pool_str}.",
                );
            case "unknown":
                throw new errors.StonfiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Stonfi.GetWalletStakesRequest} request
     * @param {Wallets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.wallets.getWalletStakes({
     *         addr_str: "addr_str"
     *     })
     */
    public getWalletStakes(
        request: Stonfi.GetWalletStakesRequest,
        requestOptions?: Wallets.RequestOptions,
    ): core.HttpResponsePromise<Stonfi.GetWalletStakesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWalletStakes(request, requestOptions));
    }

    private async __getWalletStakes(
        request: Stonfi.GetWalletStakesRequest,
        requestOptions?: Wallets.RequestOptions,
    ): Promise<core.WithRawResponse<Stonfi.GetWalletStakesResponse>> {
        const { addr_str: addrStr } = request;
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/wallets/${encodeURIComponent(addrStr)}/stakes`,
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Stonfi.GetWalletStakesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.StonfiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StonfiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.StonfiTimeoutError("Timeout exceeded when calling GET /v1/wallets/{addr_str}/stakes.");
            case "unknown":
                throw new errors.StonfiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
