/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class StonfiTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, StonfiTimeoutError.prototype);
    }
}
