/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         owner_address: "EQCM3B12QK1e4yZSf8GtBRT0aLMNyEsBc_DhVfRRtOEffLez"
 *     }
 */
export interface GetWalletAddressRequest {
    /**
     * Address of the owner
     */
    owner_address: string;
}
