/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core/index.js";
import * as Stonfi from "../../../index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Jetton {
    export interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

/**
 * Jetton specific data
 */
export class Jetton {
    protected readonly _options: Jetton.Options;

    constructor(_options: Jetton.Options) {
        this._options = _options;
    }

    /**
     * @param {string} addrStr
     * @param {Stonfi.GetWalletAddressRequest} request
     * @param {Jetton.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.jetton.getWalletAddress("addr_str", {
     *         owner_address: "EQCM3B12QK1e4yZSf8GtBRT0aLMNyEsBc_DhVfRRtOEffLez"
     *     })
     */
    public getWalletAddress(
        addrStr: string,
        request: Stonfi.GetWalletAddressRequest,
        requestOptions?: Jetton.RequestOptions,
    ): core.HttpResponsePromise<Stonfi.GetWalletAddressResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWalletAddress(addrStr, request, requestOptions));
    }

    private async __getWalletAddress(
        addrStr: string,
        request: Stonfi.GetWalletAddressRequest,
        requestOptions?: Jetton.RequestOptions,
    ): Promise<core.WithRawResponse<Stonfi.GetWalletAddressResponse>> {
        const { owner_address: ownerAddress } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["owner_address"] = ownerAddress;
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/jetton/${encodeURIComponent(addrStr)}/address`,
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Stonfi.GetWalletAddressResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.StonfiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StonfiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.StonfiTimeoutError("Timeout exceeded when calling GET /v1/jetton/{addr_str}/address.");
            case "unknown":
                throw new errors.StonfiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
