/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../../../index.js";

export interface DexSimulateSwapUtoipaResponse {
    /** Address of the wallet to which the operation is simulated */
    ask_address: string;
    /** Address of the pool's(asked) jetton wallet */
    ask_jetton_wallet: string;
    /** Token units asked */
    ask_units: string;
    /** Fee address */
    fee_address: string;
    /** fee percent */
    fee_percent: string;
    /** Fee units */
    fee_units: string;
    /** Gas params */
    gas_params: Stonfi.GasParamsSchema;
    /** Minimal amount of ask units */
    min_ask_units: string;
    /** Address of the wallet from which the operation is simulated */
    offer_address: string;
    /** Address of the pool's(offered) jetton wallet */
    offer_jetton_wallet: string;
    /** Token units offered */
    offer_units: string;
    /** Address of the pool */
    pool_address: string;
    /** Price impact */
    price_impact: string;
    /**
     * Recommended minimal amount of ask units
     * (considering potential sandwich attack)
     */
    recommended_min_ask_units: string;
    /**
     * Recommended difference between the original price of order and the final price
     * (considering potential sandwich attack)
     */
    recommended_slippage_tolerance: string;
    /** Address of the operation router */
    router_address: string;
    /** Difference between the original price of order and the final price */
    slippage_tolerance: string;
    /** Swap rate */
    swap_rate: string;
}
