/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../../../index.js";

/**
 * Use `new` function to create `PoolListResponse`, it sorts elems by popularity_index
 */
export interface GetPoolListByMarketResponse {
    pool_list: Stonfi.PoolInfoSchema[];
}
