/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../index.js";

export interface AssetInfoSchema {
    /** Asset balance */
    balance?: string | null;
    /** Asset is blacklisted */
    blacklisted: boolean;
    /** Asset is community created */
    community: boolean;
    /** Address of smart contract */
    contract_address: string;
    /** Custom payload API URI */
    custom_payload_api_uri?: string | null;
    /** Number of decimal places used to represent fractional amounts of an asset */
    decimals: number;
    /** Asset has default symbol */
    default_symbol: boolean;
    /** Asset is deprecated */
    deprecated: boolean;
    /** Ston internal asset price in USD */
    dex_price_usd?: string | null;
    /** [DEPRECATED] Ston internal asset price in USD */
    dex_usd_price?: string | null;
    /** Displayable name */
    display_name?: string | null;
    /** Comma separated list of supported extensions */
    extensions?: string[];
    /** URL to asset image */
    image_url?: string | null;
    /** Asset kind */
    kind: Stonfi.AssetKindSchema;
    /** Popularity index */
    popularity_index?: number | null;
    /** Asset priority for ease of display */
    priority: number;
    /** Asset symbol */
    symbol: string;
    /** Asset tags */
    tags: string[];
    /** Asset may have fee from the authors */
    taxable: boolean;
    /** Asset price in USD */
    third_party_price_usd?: string | null;
    /** [DEPRECATED] Asset price in USD */
    third_party_usd_price?: string | null;
    /** Asset wallet address */
    wallet_address?: string | null;
}
