/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../index.js";

export interface AssetInfoSchemaV2 {
    /** Asset balance */
    balance?: string;
    /** Address of smart contract */
    contract_address: string;
    /** Ston internal asset price in USD */
    dex_price_usd?: string;
    /** Comma separated list of supported extensions */
    extensions?: string[];
    /** Asset kind */
    kind: Stonfi.AssetKindSchema;
    /** Asset meta */
    meta?: Stonfi.AssetMetaSchemaV2;
    /** Asset priority for ease of display */
    pair_priority?: number;
    /** Asset popularity index */
    popularity_index?: number;
    /** Asset tags */
    tags?: string[];
    /** Asset wallet address */
    wallet_address?: string;
}
