/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssetInfoScreenerSchema {
    /** Circulationg supply */
    circulatingSupply?: string | null;
    /** Address of smart contract */
    id: string;
    /** Displayable name */
    name: string;
    /** Asset symbol */
    symbol: string;
    /** Total supply */
    totalSupply: string;
}
