/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AssetKindSchema = "Jetton" | "Wton" | "Ton" | "NotAnAsset";
export const AssetKindSchema = {
    Jetton: "Jetton",
    Wton: "Wton",
    Ton: "Ton",
    NotAnAsset: "NotAnAsset",
} as const;
