/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssetMetaSchemaV2 {
    /** Custom payload API URI */
    custom_payload_api_uri?: string | null;
    /** Number of decimal places used to represent fractional amounts of an asset */
    decimals?: number | null;
    /** Displayable name */
    display_name?: string | null;
    /** URL to asset image */
    image_url?: string | null;
    /** Asset symbol */
    symbol?: string | null;
}
