/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssetFeeStatsSchema {
    /** Sum of deposits */
    accrued: string;
    /** Sum of deposits in usd */
    accrued_usd?: string;
    /** Jetton master address */
    asset_address: string;
    /** Sum of withdrawals */
    withdrawn: string;
    /** Sum of withdrawals in usd */
    withdrawn_usd?: string;
}
