/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CmcPoolStats {
    /** Base token id */
    base_id: string;
    /** Base asset liquidity */
    base_liquidity: string;
    /** Base token name */
    base_name: string;
    /** Base token symbol */
    base_symbol: string;
    /** Volume of base asset */
    base_volume: string;
    /** Last asset quota price in base assets */
    last_price: string;
    /** Quote token address */
    quote_id: string;
    /** Quote asset liquidity */
    quote_liquidity: string;
    /** Quote token name */
    quote_name: string;
    /** Quote token symbol */
    quote_symbol: string;
    /** Volume of quote asset */
    quote_volume: string;
    /** URL to pool */
    url: string;
}
