/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EventType =
    | {
          eventType: "join";
      }
    | {
          eventType: "exit";
      }
    | {
          eventType: "swap";
      };
