/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../index.js";

export interface EventSchema {
    eventType?: EventSchema.EventType;
    block: Stonfi.BlockSchema;
}

export namespace EventSchema {
    export type EventType = "swap";
    export const EventType = {
        Swap: "swap",
    } as const;
}
