/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FarmMinterRewardInfoSchema {
    address: string;
    admin_fee: string;
    estimated_end_timestamp?: string | null;
    index: number;
    remaining_rewards: string;
    reward_rate_24h: string;
    /** True if pool won't distribute any more rewards */
    rewards_distributed: boolean;
    status: string;
}
