/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FarmMajorVersion = "v1" | "v2" | "v3";
export const FarmMajorVersion = {
    V1: "v1",
    V2: "v2",
    V3: "v3",
} as const;
