/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../index.js";

export interface FarmInfoSchema {
    /** True if remaining rewards can't be distributed */
    all_rewards_distributed: boolean;
    /** Annual percentage yield */
    apy?: string;
    /** Create timestamp */
    create_timestamp?: string;
    /** Custodian address */
    custodian_address: string;
    /** Locked total LP tokens */
    locked_total_lp: string;
    /** Locked total LP tokens in USD */
    locked_total_lp_usd?: string;
    /** Farm meta */
    meta?: Stonfi.FarmMinterMetaSchema;
    /** Minimal stake duration seconds */
    min_stake_duration_s: string;
    /** Address of the farm */
    minter_address: string;
    /** Farm NFT list */
    nft_infos: Stonfi.FarmNftInfoSchema[];
    /** Owner address */
    owner_address?: string;
    /** Address of the pool */
    pool_address: string;
    /** Farm rewards */
    rewards: Stonfi.FarmMinterRewardInfoSchema[];
    /** Minter status */
    status: string;
    /** Farm version */
    version: string;
}
