/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../index.js";

export interface FarmNftInfoSchema {
    /** NFT address */
    address: string;
    /** NFT creation timestamp */
    create_timestamp: string;
    /** Minimal unstake timestamp */
    min_unstake_timestamp: string;
    /** Nonclaimed rewards */
    nonclaimed_rewards: string;
    /** Farm rewards */
    rewards: Stonfi.FarmNftRewardInfoSchema[];
    /** Amount of staked tokens */
    staked_tokens: string;
    /** NFT status */
    status: string;
    /** Unstake timestamp */
    unstake_timestamp?: string;
}
