/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FarmMinterMetaSchema {
    /** Description */
    description?: string;
    /** Image */
    image?: string;
    /** Marketplace */
    marketplace?: string;
    /** Name */
    name?: string;
    social_links?: unknown;
}
