/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FarmMinterMetaSchema {
    /** Description */
    description?: string | null;
    /** Image */
    image?: string | null;
    /** Marketplace */
    marketplace?: string | null;
    /** Name */
    name?: string | null;
    /** Social links */
    social_links?: unknown;
}
