/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FeeWithdrawalSchema {
    /** Amount withdrawn */
    amount: string;
    /** Jetton master address */
    asset_address: string;
    /** Exit code */
    exit_code: string;
    /** Address of the wallet that triggered withdrawal */
    operation_wallet_address: string;
    /** Router contract handling the vault */
    router_address: string;
    /** Success of tx */
    success: boolean;
    /** Address of the vault */
    vault_address: string;
    /** Transaction hash */
    vault_tx_hash: string;
    /** Logical time of transaction */
    vault_tx_lt: number;
    /** Time withdraw transaction happened (YYYY-MM-DDTHH:MM:SS) */
    vault_tx_timestamp: string;
}
