/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GasParamsSchema {
    /** Estimated gas consumption */
    estimated_gas_consumption: string;
    /** Forward TON amount for transaction */
    forward_gas: string;
    /** Optional TON gas budget for transaction */
    gas_budget?: string | null;
}
