/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../index.js";

export interface LiquidityEvent {
    amount0: string;
    amount1: string;
    eventIndex: number;
    maker: string;
    pairId: string;
    reserves?: Stonfi.Reserves;
    txnId: string;
    txnIndex: number;
}
