/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OperationStatus {
    /** Wallet address */
    address: string;
    /** Changes in balance */
    balance_deltas: string;
    /** Transaction coins */
    coins: string;
    /** Exit code of operation */
    exit_code: string;
    /** Operation logical time */
    logical_time: string;
    /** Id of operation status query */
    query_id: string;
    /** Operation hash */
    tx_hash: number[];
}
