/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OperationStat {
    /** Address of asset0 */
    asset0_address: string;
    /** Amount of asset0 */
    asset0_amount: string;
    /** Delta of asset0 */
    asset0_delta: string;
    /** Reserve of asset0 */
    asset0_reserve: string;
    /** Address of asset1 */
    asset1_address: string;
    /** Amount of asset1 */
    asset1_amount: string;
    /** Delta of asset1 */
    asset1_delta: string;
    /** Reserve of asset1 */
    asset1_reserve: string;
    /** Address of destination wallet */
    destination_wallet_address: string;
    /** Operation exit code */
    exit_code: string;
    /** Liquidity pool fee asset address */
    fee_asset_address?: string | null;
    /** Liquidity pool fee amount */
    lp_fee_amount: string;
    /** Liquidity pool token amount change */
    lp_token_delta: string;
    /** Liquidity pool token amount supply */
    lp_token_supply: string;
    /** Type of operation */
    operation_type: string;
    /** Address of the pool */
    pool_address: string;
    /** Transaction hash */
    pool_tx_hash: string;
    /** Transaction logical time */
    pool_tx_lt: number;
    /** Transaction timestamp */
    pool_tx_timestamp: string;
    /** Protocol fee amount */
    protocol_fee_amount: string;
    /** Referral fee address */
    referral_address?: string | null;
    /** Referral fee amount */
    referral_fee_amount: string;
    /** Address of the router */
    router_address: string;
    /** Operation is successful */
    success: boolean;
    /** Wallet address */
    wallet_address: string;
    /** Transaction hash */
    wallet_tx_hash: string;
    /** Transaction logical time */
    wallet_tx_lt: string;
    /** Transaction timestamp */
    wallet_tx_timestamp: string;
}
