/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../index.js";

export interface OperationsInfo {
    asset0_info: Stonfi.AssetInfoSchema;
    asset1_info: Stonfi.AssetInfoSchema;
    operation: Stonfi.OperationStat;
}
