/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PoolInfoSchema {
    /** Address of pool */
    address: string;
    /** Stable swap amplification parameter */
    amp?: string;
    /** Annual percentage yield on the last day */
    apy_1d?: string;
    /** Annual percentage yield on the last month */
    apy_30d?: string;
    /** Annual percentage yield on the last week */
    apy_7d?: string;
    /** Protocol fee collected in token0 */
    collected_token0_protocol_fee: string;
    /** Protocol fee collected in token1 */
    collected_token1_protocol_fee: string;
    /** Pool is deprecated */
    deprecated: boolean;
    /** Account address of liquidity pool tokens */
    lp_account_address?: string;
    /** Balance of liquidity pool tokens */
    lp_balance?: string;
    /** Fee of liquidity pool token */
    lp_fee: string;
    /** Price of liquidity pool token in USD */
    lp_price_usd?: string;
    /** Total supply of liquidity pool tokens */
    lp_total_supply: string;
    /** Total supply of liquidity pool tokens in USD */
    lp_total_supply_usd?: string;
    /** Wallet address of liquidity pool tokens */
    lp_wallet_address?: string;
    /** Popularity index */
    popularity_index?: number;
    /** Fee of protocol */
    protocol_fee: string;
    /** Address of protocol fee */
    protocol_fee_address: string;
    /** Stable token ratio parameter */
    rate?: string;
    /** Referral fee */
    ref_fee?: string;
    /** Reserve of token0 in pool */
    reserve0: string;
    /** Reserve of token1 in pool */
    reserve1: string;
    /** Address of router */
    router_address: string;
    /** Address of token0 */
    token0_address: string;
    /** Balance of token0 */
    token0_balance?: string;
    /** Address of token1 */
    token1_address: string;
    /** Balance of token1 */
    token1_balance?: string;
    /** USD trade volume during last 24 hours */
    volume_24h_usd?: string;
    /** Token 0 weight parameter */
    w0?: string;
}
