/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PoolStats {
    /** Annual percentage yield */
    apy?: string | null;
    /** Base asset id */
    base_id: string;
    /** Amount of liquidity of base asset */
    base_liquidity: string;
    /** Base asset name */
    base_name: string;
    /** Base asset symbol */
    base_symbol: string;
    /** volume of base asset */
    base_volume: string;
    /** Last asset quota price in base assets */
    last_price: string;
    /** [DEPRECATED] Liquidity pool token price */
    lp_price: string;
    /** Liquidity pool token price */
    lp_price_usd: string;
    /** Address of the pool */
    pool_address: string;
    /** Quote asset id */
    quote_id: string;
    /** Amount of liquidity of quote asset */
    quote_liquidity: string;
    /** Quote asset name */
    quote_name: string;
    /** Quote asset symbol */
    quote_symbol: string;
    /** Volume of quote asset */
    quote_volume: string;
    /** Address of router */
    router_address: string;
    /** URL of the pool */
    url: string;
}
