/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PoolInfoScreenerSchema {
    /** First asset in pair address */
    asset0Id: string;
    /** First asset in pair address */
    asset1Id: string;
    /** Pool creation block number */
    createdAtBlockNumber?: number;
    /** Pool creation block number */
    createdAtBlockTimestamp?: number;
    /** Pool creation transaction id */
    createdAtTxnId?: string;
    /** Protocol fee in base points */
    feeBps?: number;
    /** Liquidity pool address */
    id: string;
}
