/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RouterTypeSchema =
    | "WeightedConstProduct"
    | "WeightedStableSwap"
    | "ConstantProduct"
    | "ConstantSum"
    | "StableSwap";
export const RouterTypeSchema = {
    WeightedConstProduct: "WeightedConstProduct",
    WeightedStableSwap: "WeightedStableSwap",
    ConstantProduct: "ConstantProduct",
    ConstantSum: "ConstantSum",
    StableSwap: "StableSwap",
} as const;
