/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../index.js";

export interface RouterInfoSchema {
    /** The address of router contract */
    address: string;
    /** Major router contract version */
    major_version: number;
    /** Minor router contract version */
    minor_version: number;
    /** If true, the router may be selected by default for initial liquidity provision */
    pool_creation_enabled: boolean;
    /** The master address of router's proxy TON */
    pton_master_address: string;
    /** Proxy TON version */
    pton_version: string;
    /** The address of router's proxy TON wallet */
    pton_wallet_address: string;
    /** Router type */
    router_type: Stonfi.RouterTypeSchema;
}
