/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StakeNft {
    address: string;
    image_url: string;
    min_unstaking_timestamp: string;
    minted_gemston: string;
    staked_tokens: string;
    staking_timestamp: string;
    status: string;
    unstake_timestamp?: string;
    voting_power: string;
}
