/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../index.js";

export interface SwapEvent {
    amount0In?: string | null;
    amount0Out?: string | null;
    amount1In?: string | null;
    amount1Out?: string | null;
    eventIndex: number;
    maker: string;
    pairId: string;
    priceNative: string;
    reserves?: Stonfi.Reserves | null;
    txnId: string;
    txnIndex: number;
}
