/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../index.js";

export interface SwapEvent {
    amount0In?: string;
    amount0Out?: string;
    amount1In?: string;
    amount1Out?: string;
    eventIndex: number;
    maker: string;
    pairId: string;
    priceNative: string;
    reserves?: Stonfi.Reserves;
    txnId: string;
    txnIndex: number;
}
