/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TxId {
    /** Transaction's contract address */
    contract_address?: string | null;
    /** Transaction's hash */
    hash: string;
    /** Transaction's logical time */
    lt: number;
}
