/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VaultSchema {
    /** Jetton master address */
    asset_address: string;
    /** Balance in jetton units */
    balance: string;
    /** Router contract handling the vault */
    router_address: string;
    /** Address of the vault */
    vault_address: string;
}
