/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WrappedLiquidityProvisionType = "Initial" | "Balanced" | "Arbitrary";
export const WrappedLiquidityProvisionType = {
    Initial: "Initial",
    Balanced: "Balanced",
    Arbitrary: "Arbitrary",
} as const;
