/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         search_string: "search_string"
 *     }
 */
export interface AssetSearchRequest {
    /**
     * Search string (by partial display name or symbol) or by full contract address
     */
    search_string: string;
    /**
     * Condition
     */
    condition?: string;
    /**
     * Unconditional assets
     */
    unconditional_asset?: string | string[];
    /**
     * Limit of assets in the response
     */
    limit?: number;
    /**
     * Wallet address
     */
    wallet_address?: string;
}
