/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface AssetQueryRequest {
    /**
     * Condition
     */
    condition?: string;
    /**
     * Unconditional assets
     */
    unconditional_asset?: string | string[];
    /**
     * Wallet address
     */
    wallet_address?: string;
}
