/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         offer_address: "EQBynBO23ywHy_CgarY9NK9FTz0yDsG82PtcbSTQgGoXwiuA",
 *         ask_address: "EQCM3B12QK1e4yZSf8GtBRT0aLMNyEsBc_DhVfRRtOEffLez",
 *         units: "300",
 *         slippage_tolerance: "0.001",
 *         pool_address: "EQAKleHU6-eGDQUfi4YXMNve4UQP0RGAIRkU4AiRRlgDUbaM"
 *     }
 */
export interface DexReverseSimulateSwapUtoipaRequest {
    /**
     * The address of the token we want to sell
     */
    offer_address: string;
    /**
     * The address of the token we want to buy
     */
    ask_address: string;
    /**
     * Number of token units we want to buy
     */
    units: string;
    /**
     * The maximum possible difference between the rates that we expect and which will actually be, in fractions (for example, 0.001 is 0.1%)
     */
    slippage_tolerance: string;
    pool_address?: string;
    /**
     * Referral address
     */
    referral_address?: string;
    /**
     * Referral fee in base points
     */
    referral_fee_bps?: string;
    /**
     * If true V2 routers might be selected for the swap. Default: true
     */
    dex_v2?: boolean;
    /**
     * Allows to restrict exact DEX version (or multiple)
     */
    dex_version?: string | string[];
}
