/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         router_address: "EQB3ncyBUTjZUA5EnFKR5_EnOMI9V1tTEAAPaiU71gc4TiUt",
 *         owner_address: "EQCM3B12QK1e4yZSf8GtBRT0aLMNyEsBc_DhVfRRtOEffLez",
 *         query_id: "1"
 *     }
 */
export interface DexSwapStatusRequest {
    /**
     * Address of the operation router
     */
    router_address: string;
    /**
     * Owner`s wallet address
     */
    owner_address: string;
    /**
     * Id of operation status query
     */
    query_id: string;
}
