/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stonfi from "../../../../index.js";

/**
 * @example
 *     {
 *         provision_type: "Initial",
 *         token_a: "EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c",
 *         token_b: "EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs",
 *         slippage_tolerance: "0.001"
 *     }
 */
export interface DexSimulateLiquidityProvisionRequest {
    /**
     * Determines liquidity strategy:
     * - "Initial": Create new pool (requires both token amounts)
     * - "Balanced": Add to existing pool at current ratio (auto-calculates one token amount)
     * - "Arbitrary": Add liquidity in any ratio to existing pool (requires explicit amounts)
     */
    provision_type: Stonfi.WrappedLiquidityProvisionType;
    /**
     * Required for Balanced/Arbitrary provision.
     * Specifies existing pool address for liquidity operations.
     */
    pool_address?: string | null;
    /**
     * User's wallet address for balance checks (optional).
     * When provided, returns current LP account balances if exists.
     */
    wallet_address?: string | null;
    /**
     * Token A address for the liquidity pair (always required)
     */
    token_a: string;
    /**
     * Token B address for the liquidity pair (always required)
     */
    token_b: string;
    /**
     * Token A amount rules:
     * - Initial/Arbitrary: REQUIRED
     * - Balanced: Provide EITHER this OR token_b_units (auto-calculates the other)
     */
    token_a_units?: string | null;
    /**
     * Token B amount rules:
     * - Initial/Arbitrary: REQUIRED
     * - Balanced: Provide EITHER this OR token_a_units (auto-calculates the other)
     */
    token_b_units?: string | null;
    /**
     * Maximum acceptable price impact (0.001 = 0.1%).
     * Affects minimum liquidity thresholds in response.
     */
    slippage_tolerance: string;
}
