/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         addr_str: "addr_str"
 *     }
 */
export interface GetAssetRequest {
    addr_str: string;
}
