/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         pool_addr_str: "pool_addr_str"
 *     }
 */
export interface GetFarmsByPoolRequest {
    pool_addr_str: string;
}
