/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         asset_0_addr_str: "asset_0_addr_str",
 *         asset_1_addr_str: "asset_1_addr_str"
 *     }
 */
export interface GetPoolListByMarketRequest {
    asset_0_addr_str: string;
    asset_1_addr_str: string;
}
