/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetRouterListRequest {
    /**
     * If true V2 routers will be present in the response. Default: true
     */
    dex_v2?: boolean | null;
}
