/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface PoolQueryRequest {
    /**
     * Condition
     */
    condition?: string | null;
    /**
     * Unconditional assets
     */
    unconditional_asset?: string | string[];
    /**
     * Wallet address
     */
    wallet_address?: string | null;
    /**
     * If true V2 pools will be present in the response. Default: true
     */
    dex_v2?: string | null;
}
