/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { StonfiClient } from "../../src/Client";

describe("Jetton", () => {
    test("get_wallet_address", async () => {
        const server = mockServerPool.createServer();
        const client = new StonfiClient({ environment: server.baseUrl });

        const rawResponseBody = { address: "address" };
        server
            .mockEndpoint()
            .get("/v1/jetton/addr_str/address")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jetton.getWalletAddress("addr_str", {
            owner_address: "EQCM3B12QK1e4yZSf8GtBRT0aLMNyEsBc_DhVfRRtOEffLez",
        });
        expect(response).toEqual({
            address: "address",
        });
    });
});
