/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetDexStatsRequest {
    /**
     * Time since stats are requested (YYYY-MM-DDTHH:MM:SS)
     */
    since?: string | null;
    /**
     * Time until stats are requested (YYYY-MM-DDTHH:MM:SS)
     */
    until?: string | null;
}
