/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         referrer_address: "EQCwiRZrfUSlMM0dz-Hm4KW1IqaFz1Pwxg3-t0jQDt36qOar",
 *         since: "2025-04-01T12:00:00",
 *         until: "2025-04-03T13:00:00"
 *     }
 */
export interface GetFeesStatsRequest {
    /**
     * Address of referrer
     */
    referrer_address: string;
    /**
     * The start of time range (YYYY-MM-DDTHH:MM:SS)
     */
    since: string;
    /**
     * The end of time range (YYYY-MM-DDTHH:MM:SS)
     */
    until: string;
}
