/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         since: "2023-06-01T12:34:56",
 *         until: "2023-06-02T23:59:59"
 *     }
 */
export interface GetPoolStatsUtoipaRequest {
    /**
     * Time since the stats are requested (YYYY-MM-DDTHH:MM:SS)
     */
    since: string;
    /**
     * Time until pool stats are requested (YYYY-MM-DDTHH:MM:SS)
     */
    until: string;
    /**
     * Exact pool addresses to filter the results. If not provided, all pools are included.
     */
    pool_address?: string | string[];
}
